site_name: Dotfiles
site_url: https://dotfiles.entelecheia.ai
site_author: Young Joon Lee <entelecheia@hotmail.com>
site_description: >-
  Dotfiles are configuration files that are used to customize your shell and other applications. Dotfiles are a great way to standardize your development environment. You can use the same dotfiles in your local development environment, in your CI/CD pipeline, and in your production environment.
# Repository
repo_name: entelecheia/dotfiles
repo_url: https://github.com/entelecheia/dotfiles
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2022 - 2023 Young Joon Lee

plugins:
  - search
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
theme:
  name: material
  favicon: https://assets.entelecheia.ai/favicon.png # favicon: Path to the favicon image
  logo: https://assets.entelecheia.ai/favicon.png # logo: Path to the book logo
  palette:
    scheme: slate
  features:
    - navigation.expand
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    - navigation.indexes

extra:
  analytics:
    provider: google
    property: G-VMN7QWCMSV
nav:
  - Home: index.md
  - Features: features.md
  - Usage:
    - usage/index.md
    - Configuration: usage/configuration.md
    - Update: usage/update.md
    - Dotdrop: usage/dotdrop.md
    - GitHub: usage/github.md
    - SSH, GPG, and AGE: usage/ssh-gpg-age.md
    - Pass and Passage: usage/pass.md
    - Dockerfiles: usage/dockerfiles.md
  - References: references.md
