site_name: Dotfiles
plugins:
  - search
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
theme:
  name: material
  palette:
    scheme: slate
extra:
  analytics:
    provider: google
    property: G-VMN7QWCMSV
