site_name: Dotfiles
plugins:
  - search
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
theme:
  name: material
  favicon: https://assets.entelecheia.ai/favicon.png # favicon: Path to the favicon image
  logo: https://assets.entelecheia.ai/favicon.png # logo: Path to the book logo
  palette:
    scheme: slate
  features:
    - navigation.expand
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
extra:
  analytics:
    provider: google
    property: G-VMN7QWCMSV
nav:
  - Home: index.md
  - Usage: usage.md
  - References: references.md
