DOTFILES_VERSION: 0.10.1
packages:
  - name: 1password-cli
    apt: true
    brewcask: true
  - name: age
    brew: true
    snap: true
  - name: apt-transport-https
    apt: true
  - name: autorestic
    brew: true
  - name: bazel
    apt: true
  - name: build-essential
    apt: true
  - name: code
    apt: true
  - name: code-cli
    brew: true
  - name: commitizen
    pip-user: true
    pipx: true
  - name: containerd.io
    apt: true
  - name: coreutils
    brew: true
  - name: copier
    brew: true
    pip-user: true
    pipx: true
  - name: direnv
    apt: true
    brew: true
  - name: docker-ce
    apt: true
  - name: docker-ce-cli
    apt: true
  - name: docker-compose-plugin
    apt: true
  - name: doppler
    apt: true
  - name: dopplerhq/cli/doppler
    brew: true
  - name: dotdrop
    brew: true
    pip-user: true
    pipx: true
  - name: file
    apt: true
  - name: findutils
    brew: true
  - name: font-fira-code
    brewcask: true
  - name: font-fira-code-nerd-font
    brewcask: true
  - name: fzf
    apt: true
    brew: true
  - name: gh
    apt: true
    brew: true
  - name: gitmojify
    pip-user: true
    pipx: true
  - name: git-sizer
    apt: true
    brew: true
  - name: git-workspace
    brew: true
  - name: google-perftools
    apt: true
  - name: gnupg
    brew: true
  - name: go
    brew: true
    snap: true
  - name: go-task
    brew: true
    snap: true
  - name: gpa
    apt: true
  - name: gpg-suite
    script: true
  - name: helm
    apt: true
    brew: true
  - name: jq
    apt: true
    brew: true
  - name: locales
    apt: true
  - name: locales-all
    apt: true
  - name: lsb-release
    apt: true
  - name: microk8s
    brew: true
    snap: true
  - name: mypy
    pip-user: true
    pipx: true
  - name: ngrok
    snap: true
  - name: node
    apt: true
    brew: true
  - name: nvm
    script: true
  - name: openssh-server
    apt: true
  - name: pass
    apt: true
    brew: true
  - name: pinentry-curses
    apt: true
  - name: pinentry-mac
    brew: true
  - name: pip
    pip-user: true
  - name: pipx
    brew: true
    pip-user: true
  - name: poetry
    brew: true
    snap: true
  - name: poethepoet
    brew: true
    pip-user: true
    pipx: true
  - name: pre-commit
    pip-user: true
    pipx: true
  - name: procps
    apt: true
  - name: python3-dev
    apt: true
  - name: python3-pip
    apt: true
  - name: python3-setuptools
    apt: true
  - name: python3-testresources
    apt: true
  - name: python3-venv
    apt: true
  - name: restic
    brew: true
  - name: rust
    snap: true
  - name: sdkman
    snap: true
  - name: seahorse
    apt: true
  - name: serviceman
    webi: true
  - name: setuptools
    pip-user: true
  - name: snapd
    apt: true
  - name: sops
    brew: true
    snap: true
  - name: stow
    apt: true
    brew: true
  - name: tree
    apt: true
    brew: true
  - name: tmux
    apt: true
    brew: true
  - name: tzdata
    apt: true
  - name: unzip
    apt: true
    brew: true
  - name: vim
    apt: true
  - name: xclip
    apt: true
  - name: yq
    brew: true
    snap: true
  - name: webi
    snap: true
  - name: zip
    apt: true
  - name: zsh
    apt: true
    brew: true
