name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        variant: [devcontainer, wsl, gnome]
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]
        include:
          - variant: macos
            os: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          scripts/test.sh --variant "${{ matrix.variant }}" --os "${{ matrix.os }}"
