---
name: semantic-release

on:
  workflow_call:
  workflow_dispatch:
  workflow_run:
    workflows: ["test"]
    branches: [main]
    types:
      - completed

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    # Name the Job
    name: semantic-release-test
    # check if the workflow result is success
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # Set the agent to run on
    runs-on: ubuntu-latest

    # Load all steps #
    steps:
      # Checkout the code base #
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # set env variable
      - name: Set env variable
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      # semantic prerelease
      - name: Python Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          additional_options: --verbosity=DEBUG --define=branch=${{ env.BRANCH }}
