name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        variant: [devcontainer, wsl, gnome]
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]
        include:
          - variant: darwin
            os: macos-latest
          # - variant: devcontainer
          #   os: ubuntu-20.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: install dependencies for MacOS
        if: matrix.variant == 'darwin'
        run: |
          brew install coreutils
          echo "$PWD"

      - name: Run tests
        run: |
          scripts/test_for_ci.sh --variant "${{ matrix.variant }}" --os "${{ matrix.os }}"
